name: Build and Release cloudflared for FreeBSD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check update
        id: check
        run: |
          chmod +x ./check_update.sh
          echo "TAG=$(./check_update.sh)" >> $GITHUB_OUTPUT

      - name: Update If needs - NOCGO Version
        if: steps.check.outputs.TAG != 'NULL'
        run: |
          sudo apt-get update
          sudo apt-get install -y golang-go make wget git

          git clone --branch "${{ steps.check.outputs.TAG }}" https://github.com/cloudflare/cloudflared.git
          cd cloudflared/
          wget -O "freebsd.patch" https://raw.githubusercontent.com/robvanoostenrijk/cloudflared-freebsd/refs/heads/master/freebsd.patch
          patch -p1 < ./freebsd.patch

          # cross-compile disabled CGO
          export TARGET_OS=freebsd
          export TARGET_ARCH=amd64

          # make install-go # Use Cloudflare Go
          make cloudflared
          mv ./cloudflared ./cloudflared_NOCGO

      - name: Update If needs - CGO Version
        if: steps.check.outputs.TAG != 'NULL'
        uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: freebsd
          version: '14.1'
          run: |
            sudo pkg update
            sudo pkg install -y gcc gmake go git wget

            # Build environment alreay sync
            # And NO build params need to be set
            cd cloudflared/
            gmake cloudflared

      - name: Create Release
        if: steps.check.outputs.TAG != 'NULL'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check.outputs.TAG }}
          files: |
            ./cloudflared/cloudflared
            ./cloudflared/cloudflared_NOCGO
