name: Build and Release cloudflared for FreeBSD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check update
        id: check
        run: |
          chmod +x ./check_update.sh
          echo "TAG=$(./check_update.sh)" >> $GITHUB_OUTPUT

      - name: Update If needs
        if: steps.check.outputs.TAG != 'NULL'
        run: |
          sudo apt update
          sudo apt install -y build-essential golang-go

          git clone --branch "${{ steps.check.outputs.TAG }}" https://github.com/cloudflare/cloudflared.git
          cd cloudflared/
          wget -O "freebsd.patch" https://raw.githubusercontent.com/robvanoostenrijk/cloudflared-freebsd/refs/heads/master/freebsd.patch
          patch -p1 < ./freebsd.patch

          # Disable CGO
          export CGO_ENABLED=0
          export TARGET_OS=freebsd
          export TARGET_ARCH=amd64

          ./.teamcity/install-cloudflare-go.sh
          export PATH="/tmp/go/bin:$PATH"
          make cloudflared
          sudo mv ./cloudflared /cloudflared

      - name: Create Release
        if: steps.check.outputs.TAG != 'NULL'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check.outputs.TAG }}
          files: /cloudflared
