name: Build and Release cloudflared for FreeBSD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check update
        id: check
        run: |
          chmod +x ./check_update.sh
          echo "TAG=$(./check_update.sh)" >> $GITHUB_OUTPUT

      - name: Update If needs - NOCGO Version
        if: steps.check.outputs.TAG != 'NULL'
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget git

          git clone --branch "${{ steps.check.outputs.TAG }}" https://github.com/cloudflare/cloudflared.git
          cd cloudflared/
          patch -p1 < ../freebsd.patch
          mv diagnostic/system_collector_linux.go diagnostic/system_collector_unix.go

          wget https://go.dev/dl/go1.26.3.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go1.26.3.linux-amd64.tar.gz
          export PATH=/usr/local/go/bin:$PATH

          # cross-compile disabled CGO
          export TARGET_OS=freebsd
          export TARGET_ARCH=amd64
          export GOTOOLCHAIN=local

          # make install-go # Use Cloudflare Go
          make cloudflared
          mv ./cloudflared ./cloudflared_NOCGO

      - name: Update If needs - CGO Version
        if: steps.check.outputs.TAG != 'NULL'
        uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: freebsd
          version: '14.1'
          run: |
            sudo env IGNORE_OSVERSION=yes pkg update
            sudo pkg install -y gmake git wget

            # build environment has been synchronized
            cd cloudflared/
            wget https://go.dev/dl/go1.26.3.freebsd-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.26.3.freebsd-amd64.tar.gz
            export PATH=/usr/local/go/bin:$PATH

            export GOTOOLCHAIN=local
            gmake cloudflared

      - name: Create Release
        if: steps.check.outputs.TAG != 'NULL'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check.outputs.TAG }}
          files: |
            ./cloudflared/cloudflared
            ./cloudflared/cloudflared_NOCGO
